[project]
name = "pycharm-ddd-toolkit"
version = "0.1.0"
description = "Connexion documentation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.7.1",
    "mkdocs-mermaid2-plugin>=1.2.3",
]
